CREATE TABLE AIRCOMPANY(ID INT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE PLANE(ID INT PRIMARY KEY, NAME VARCHAR(255), TYPE VARCHAR(255), SEATING_CAPACITY INT, CARRYING_CAPACITY INT, RANGE INT, AIRCOMPANY_ID INT);

insert into AIRCOMPANY (id,name) values(1,'BelAvia');
insert into PLANE (ID ,NAME ,TYPE ,SEATING_CAPACITY ,CARRYING_CAPACITY, RANGE ,AIRCOMPANY_ID ) values(1,'Boeing 777','Passenger Plane', 300,0,10000,1);
insert into PLANE (ID ,NAME ,TYPE ,SEATING_CAPACITY ,CARRYING_CAPACITY, RANGE, AIRCOMPANY_ID ) values(2,'Boeing 747','Passenger Plane', 350,0,10000,1);
insert into PLANE (ID ,NAME ,TYPE ,SEATING_CAPACITY ,CARRYING_CAPACITY, RANGE, AIRCOMPANY_ID ) values(3,'Boeing C17','Cargo Plane', 0,1000,10000,1);